version: "3.7"
services:
    app:
        build:
            args:
                user: viz
                uid: 1000
            context: ./
            dockerfile: .docker/nginx/Dockerfile
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/
        environment:
            - DB_HOST=postgres
        volumes:
            - ./:/var/www
        networks:
            - viz-net
        links:
            - postgres

    nginx:
        image: nginx:alpine
        container_name: nginx1
        restart: unless-stopped
        ports:
            - ${APP_PORT}:80
        volumes:
            - ./:/var/www
            - .docker/nginx/app.local.conf:/etc/nginx/conf.d/default.conf
        networks:
            - viz-net

    postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: vizitka
        ports:
            - ${POSTGRESS_PORT}:5432
        networks:
            - viz-net
        restart: unless-stopped

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - ${ADMINER_PORT}:8080
        links:
            - postgres
        networks:
            - viz-net

networks:
    viz-net:
        driver: bridge
