version: "3.7"
services:
  app:
    build:
      args:
        user: viz
        uid: 1000
      context: ./
      dockerfile: .docker/nginx/Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    working_dir: /opt/vizitka
    environment:
      - DB_HOST=postgres
    volumes:
      - ./:/opt/vizitka
    networks:
      - viz-net
    ports:
      - 127.0.0.1:9000:9000
    links:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14.2-bullseye
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: vizitka
    networks:
      - viz-net
    restart: unless-stopped
    volumes:
      - vizitka-back-db:/var/lib/postgresql/data

  redis:
    container_name: redis-viz
    image: redis:alpine
    restart: unless-stopped
    networks:
      - viz-net

  app-horizon:
    image: viz-backend_app
    entrypoint: /entrypoint-horizon
    container_name: app-horizon
    restart: always
    command: php -dmemory_limit=512M artisan horizon
    working_dir: /var/www/
    environment:
      - DB_HOST=postgres
    volumes:
      - ./:/var/www
    depends_on:
      - app
    networks:
      - viz-net


networks:
  viz-net:
    driver: bridge
volumes:
  vizitka-back-db:
