#!/bin/sh
set -e

while ! nc -z postgres 5432; do
  sleep 0.1
done

>&2 echo "Database is up - executing command"

>&2 echo --- composer auth config ---
composer config http-basic.nova.laravel.com admin@vizitka.bz mtDM9TlJgNdBqG9H
>&2 echo --- composer install ---
composer install
>&2 echo --- php artisan key:generate ---
php artisan key:generate
>&2 echo --- php artisan storage:link ---
php artisan storage:link
echo --- php artisan migrate ---
php artisan migrate
#>&2 echo --- php artisan migrate:refresh --seed ---
#php artisan migrate:refresh --seed
#>&2 echo --- php artisan schedule:run ---
#php artisan schedule:run
>&2 echo --- remove assets ---
rm -f storage/app/public/images/card_backgrounds/*
rm -f storage/app/public/images/onboarding/*
>&2 echo --- move assets ---
mkdir -p storage/app/public/images/card_backgrounds
mkdir -p storage/app/public/images/onboarding
mkdir -p storage/app/public/images/default
cp -r resources/images/card_background/*.jpg storage/app/public/images/card_backgrounds/
cp -r resources/images/onboarding/*.svg storage/app/public/images/onboarding/
cp -r resources/images/default/*.png storage/app/public/images/default/
>&2 echo --- move deep linking assets ---
mkdir -p storage/app/public/deep_link_files
cp -r resources/deep_link_files/apple-app-site-association.json storage/app/public/deep_link_files/apple-app-site-associations.json
cp -r resources/deep_link_files/assetlinks.json storage/app/public/deep_link_files/assetlinks.json
#>&2 echo --- php artisan lrd:generate ---
#php artisan lrd:generate

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- php-fpm "$@"
fi

exec "$@"
